// HIGHLIGHTSTART-installationIOS
platform :ios, '13.0'
// HIGHLIGHTEND-installationIOS
source 'https://github.com/CocoaPods/Specs.git'

target 'Web3AuthSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  // HIGHLIGHTSTART-installationPodfile
  pod 'Web3Auth'
  // HIGHLIGHTEND-installationPodfile
end
