export const chainIdMap = {
  ETH: "0x1",
  SOL: "0x1",
  MATIC: "0x89",
  BNB: "0x38",
  AVAX: "0xA86A",
  ARB: "0xA4B1",
  OP: "0xA",
  CRO: "0x19",
  ONE: "0x63564c40",
  CELO: "0xa4ec",
  GLMR: "0x504",
  MOVR: "Ox505",
  KLAY: "0x2019",
};

export const rpcTargetMap = {
  ETH: "https://rpc.ankr.com/eth",
  SOL: "https://rpc.ankr.com/solana",
  MATIC: "https://rpc-mainnet.matic.network",
  BNB: "https://bsc-dataseed.binance.org/",
  AVAX: "api.avax.network/ext/bc/C/rpc",
  ARB: "https://arb1.arbitrum.io/rpc",
  OP: "https://mainnet.optimism.io",
  CRO: "https://evm.cronos.org",
  ONE: "https://rpc.ankr.com/harmony",
  CELO: "https://rpc.ankr.com/celo",
  GLMR: "https://rpc.ankr.com/moonbeam",
  MOVR: "https://moonriver.public.blastapi.io",
  KLAY: "https://public-node-api.klaytnapi.com/v1/cypress",
};
