export const PLACEHOLDERS = {
  CONSTRUCTOR_CODE: "getConstructorCode",
  INIT_CODE: "getInitCode",
  LOGIN_CODE: "getLoginCode",
  MODULE_IMPORT: "getModuleImport",
  OPENLOGIN_ADAPTER: "getOpenloginAdapter",
  PACKAGE_JSON: "getPackageJson",
  RPC_FUNCTIONS: "getRPCFunctions",
  RPC_FUNCTIONS_BUTTONS: "getRPCFunctionsButtons",
  WEB3AUTH_STATE: "getWeb3AuthState",
  RPC_FUNCTIONS_RETURNS_VUE: "getRPCFunctionsReturnsVue",
  SCRIPT_IMPORT: "getScriptImport",
  RN_RESOLVED_REDIRECT_URL: "getRNResolvedRedirectUrl",
  ANDROID_LOGIN_CONFIG: "getAndroidLoginConfig",
  FLUTTER_LOGIN_CONFIG: "getFlutterLoginConfig",
  IOS_LOGIN_CONFIG: "getIOSLoginConfig",
  WEB3AUTH_OPTIONS: "Web3AuthOptions",
  LOGIN_CONFIG: "LoginParams",
  EVM_PROVIDER: "EVMProvider",
};
