name: Check External links

on:
  push:
    branches:
      - master
  pull_request:
    types: [labeled]

jobs:
  markdown-link-check:
    if: ${{ contains(github.event.pull_request.labels.*.name, 'check-links') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check markdown links
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          file-extension: .mdx
          use-quiet-mode: yes
